import { Body, Controller, Get, HttpCode, HttpStatus, Param, Post, Query } from '@nestjs/common';
import { ApiBearerAuth, ApiHeader, ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import { Throttle } from '@nestjs/throttler';
import { CurrentUser, IdempotencyKey } from 'src/common/decorators/auth.decorators';
import { CursorPaginationDto } from 'src/common/dto/pagination.dto';
import { BadRequestException } from 'src/common/exceptions/app-exceptions';
import { CheckInsService } from './check-ins.service';
import { CreateCheckInDto } from './dto/check-in.dto';

@ApiTags('check-ins')
@ApiBearerAuth()
@Controller()
export class CheckInsController {
  constructor(private readonly checkIns: CheckInsService) {}

  @Post('check-ins')
  @HttpCode(HttpStatus.ACCEPTED)
  /** Generous enough for a real day of travel, tight enough to stop scripted farming. */
  @Throttle({ default: { limit: 20, ttl: 3_600_000 } })
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description:
      'A UUID generated by the client per submission attempt and reused across ' +
      'retries. Mandatory: it is what makes a retry over a bad connection safe.',
  })
  @ApiOperation({
    summary: 'Submit a check-in',
    description:
      'Returns 202 with `status: "pending"`. The geofence, capture-window and ' +
      'in-app-camera checks run synchronously, so a 422 means "this will never ' +
      'succeed, tell the user now". Everything else — duplicate-photo detection, ' +
      'impossible-velocity, trust routing — resolves asynchronously; poll ' +
      '`GET /check-ins/:id` or wait for the push notification.\n\n' +
      '`estimatedPoints` is what the check-in will pay if it verifies, so the ' +
      'client can show the number immediately.',
  })
  @ApiResponse({ status: 202, description: 'Accepted and queued for verification.' })
  @ApiResponse({ status: 409, description: 'Already checked in here today, or cooldown active.' })
  @ApiResponse({ status: 422, description: 'Outside the geofence, stale photo, or gallery image.' })
  submit(
    @Body() dto: CreateCheckInDto,
    @CurrentUser('id') userId: string,
    @IdempotencyKey() idempotencyKey?: string,
  ) {
    if (!idempotencyKey) {
      throw new BadRequestException(
        'An Idempotency-Key header is required on check-in submission.',
        'idempotency_key_required',
      );
    }
    return this.checkIns.submit(userId, dto, idempotencyKey);
  }

  @Get('check-ins/:id')
  @ApiOperation({
    summary: 'Check-in status',
    description: 'Only the owner can read a check-in; anything else returns 404.',
  })
  findOne(@Param('id') id: string, @CurrentUser('id') userId: string) {
    return this.checkIns.findOne(id, userId);
  }

  @Get('me/check-ins')
  @ApiOperation({ summary: 'The requesting user’s check-in history' })
  list(@CurrentUser('id') userId: string, @Query() query: CursorPaginationDto) {
    return this.checkIns.listForUser(userId, query.limit, query.cursor);
  }
}
