/**
 * One-off: resolve a freely-licensed Commons photo for each destination seed.
 *
 * Writes src/mocks/seed/images.ts. Re-run if the catalogue grows. Anything that
 * does not resolve to a genuinely free licence is left out, and the destination
 * keeps its generated gradient panel — we do not guess attribution.
 */

const TITLES = {
  "khajuraho-monuments": "Khajuraho Group of Monuments",
  "mahakaleshwar-ujjain": "Mahakaleshwar Jyotirlinga",
  "sanchi-stupa": "Sanchi",
  orchha: "Orchha",
  "gwalior-fort": "Gwalior Fort",
  "bandhavgarh-national-park": "Bandhavgarh National Park",
  "kanha-national-park": "Kanha Tiger Reserve",
  pachmarhi: "Pachmarhi",
  "bhimbetka-rock-shelters": "Bhimbetka rock shelters",
  mandu: "Mandu, Madhya Pradesh",
  omkareshwar: "Omkareshwar",
  "bhedaghat-dhuandhar": "Bhedaghat",
  "bhojpur-temple": "Bhojeshwar Temple",
  chanderi: "Chanderi",
  maheshwar: "Maheshwar",
  "satpura-national-park": "Satpura National Park",
  "pench-national-park": "Pench National Park",
  amarkantak: "Amarkantak",
  sonagiri: "Sonagiri",
  "udayagiri-caves": "Udayagiri Caves",
  "kuno-national-park": "Kuno National Park",
  "chausath-yogini-mitaoli": "Chausath Yogini Temple, Morena",
  "bateshwar-temples": "Bateshwar Hindu temples, Morena",
  "garhkundar-fort": "Garh Kundar",
  bhimkund: "Bhimkund",
  "dhamnar-caves": "Dhamnar",
  patalkot: "Patalkot",
  "bagh-caves": "Bagh Caves",
  "ginnorgarh-fort": "Ginnorgarh",
};

/**
 * Destinations whose Wikipedia article has no lead image. Files picked by hand
 * from Commons search; licence is still verified below, never assumed.
 */
const FILES = {
  "bateshwar-temples": "Bateshwar Group of Temples, Morena, Near Gwalior.jpg",
  "dhamnar-caves": "Dhamnar Caves overview.jpg",
  patalkot: "Patalkot Green Valley View, Chhindwara District, Madhya Pradesh, India.jpg",
};

const FREE = /^(cc0|cc[ -]|public domain|pd[- ]|gfdl|fal)/i;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Commons rate-limits anonymous bursts; back off and retry rather than dropping rows. */
async function get(url, attempt = 0) {
  const res = await fetch(url, {
    headers: { "User-Agent": "YatraGo/0.1 (seed tooling; contact: team@yatrago.example)" },
  });
  const text = await res.text();
  try {
    return JSON.parse(text);
  } catch {
    if (attempt >= 5) throw new Error(`non-JSON after ${attempt} retries: ${text.slice(0, 60)}`);
    await sleep(2000 * 2 ** attempt);
    return get(url, attempt + 1);
  }
}

/** Canonical upload host, no analytics query string. */
const clean = (u) => (u ?? "").split("?")[0].replace("//thumb.wikimedia.org/", "//upload.wikimedia.org/");

const strip = (html) =>
  (html ?? "")
    .replace(/<[^>]*>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#0?39;/g, "'")
    .replace(/\s+/g, " ")
    .trim();

async function leadImage(title) {
  const r = await get(
    `https://en.wikipedia.org/w/api.php?action=query&prop=pageimages&format=json&pithumbsize=1600&redirects=1&titles=${encodeURIComponent(title)}`,
  );
  const page = Object.values(r.query?.pages ?? {})[0];
  return page?.pageimage ?? null;
}

async function commonsMeta(file) {
  const r = await get(
    `https://commons.wikimedia.org/w/api.php?action=query&prop=imageinfo&format=json&iiprop=url|extmetadata|size&iiurlwidth=1600&titles=${encodeURIComponent(`File:${file}`)}`,
  );
  const page = Object.values(r.query?.pages ?? {})[0];
  const info = page?.imageinfo?.[0];
  if (!info) return null;
  const m = info.extmetadata ?? {};
  return {
    url: clean(info.thumburl ?? info.url),
    width: info.thumbwidth ?? info.width,
    height: info.thumbheight ?? info.height,
    artist: strip(m.Artist?.value) || "Unknown",
    licence: strip(m.LicenseShortName?.value) || "Unknown",
    descriptionUrl: info.descriptionurl,
  };
}

const out = {};
for (const [slug, title] of Object.entries(TITLES)) {
  try {
    const file = FILES[slug] ?? (await leadImage(title));
    if (!file) {
      console.warn(`SKIP ${slug}: no lead image on "${title}"`);
      continue;
    }
    const meta = await commonsMeta(file);
    if (!meta) {
      console.warn(`SKIP ${slug}: no Commons metadata for ${file}`);
      continue;
    }
    if (!FREE.test(meta.licence)) {
      console.warn(`SKIP ${slug}: licence "${meta.licence}" is not clearly free`);
      continue;
    }
    out[slug] = meta;
    console.log(`OK   ${slug}  ${meta.licence}  ${meta.artist.slice(0, 48)}`);
  } catch (e) {
    console.warn(`FAIL ${slug}: ${e.message}`);
  }
  await sleep(700);
}

const header = `/**
 * Hero imagery — GENERATED by scripts/fetch-images.mjs. Do not hand-edit.
 *
 * Every entry is a Wikimedia Commons file under a verified free licence, with
 * the author and file page recorded so attribution renders from data rather
 * than being asserted in code. Destinations absent from this map fall back to
 * the generated gradient panel in components/public/photo.tsx.
 *
 * Resolved ${Object.keys(out).length}/${Object.keys(TITLES).length} on ${new Date().toISOString().slice(0, 10)}.
 */

export interface SeedImage {
  url: string;
  width: number;
  height: number;
  attribution: string;
  licence: string;
  sourceUrl: string;
}

export const destinationImages: Record<string, SeedImage> = `;

const body = JSON.stringify(
  Object.fromEntries(
    Object.entries(out).map(([slug, m]) => [
      slug,
      {
        url: m.url,
        width: m.width,
        height: m.height,
        attribution: m.artist,
        licence: m.licence,
        sourceUrl: m.descriptionUrl,
      },
    ]),
  ),
  null,
  2,
);

const { writeFileSync } = await import("node:fs");
writeFileSync(
  new URL("../src/mocks/seed/images.ts", import.meta.url),
  `${header}${body};\n`,
);

console.log(`\nResolved ${Object.keys(out).length}/${Object.keys(TITLES).length} → src/mocks/seed/images.ts`);
