/**
 * Hero imagery — GENERATED by scripts/fetch-images.mjs. Do not hand-edit.
 *
 * Every entry is a Wikimedia Commons file under a verified free licence, with
 * the author and file page recorded so attribution renders from data rather
 * than being asserted in code. Destinations absent from this map fall back to
 * the generated gradient panel in components/public/photo.tsx.
 *
 * Resolved 29/29 on 2026-09-20.
 */

export interface SeedImage {
  url: string;
  width: number;
  height: number;
  attribution: string;
  licence: string;
  sourceUrl: string;
}

export const destinationImages: Record<string, SeedImage> = {
  "khajuraho-monuments": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/1_Khajuraho.jpg/1920px-1_Khajuraho.jpg",
    "width": 1600,
    "height": 1117,
    "attribution": "PLBechly",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:1_Khajuraho.jpg"
  },
  "mahakaleshwar-ujjain": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Mahakaleshwar_Temple%2C_Ujjain.jpg/1920px-Mahakaleshwar_Temple%2C_Ujjain.jpg",
    "width": 1600,
    "height": 900,
    "attribution": "Ashverse",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mahakaleshwar_Temple,_Ujjain.jpg"
  },
  "sanchi-stupa": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/East_Gateway_-_Stupa_1_-_Sanchi_Hill_2013-02-21_4398.JPG/1920px-East_Gateway_-_Stupa_1_-_Sanchi_Hill_2013-02-21_4398.JPG",
    "width": 1600,
    "height": 2409,
    "attribution": "Biswarup Ganguly",
    "licence": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:East_Gateway_-_Stupa_1_-_Sanchi_Hill_2013-02-21_4398.JPG"
  },
  "orchha": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Chaturbhuj_Temple%2C_Orchha.jpg/1920px-Chaturbhuj_Temple%2C_Orchha.jpg",
    "width": 1600,
    "height": 1200,
    "attribution": "Yann (talk)",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chaturbhuj_Temple,_Orchha.jpg"
  },
  "gwalior-fort": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Gwalior_Fort_front.jpg/1920px-Gwalior_Fort_front.jpg",
    "width": 1600,
    "height": 1067,
    "attribution": "Anuppyr007",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gwalior_Fort_front.jpg"
  },
  "bandhavgarh-national-park": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Tigress_in_Bandhavgarh_NP.jpg/1920px-Tigress_in_Bandhavgarh_NP.jpg",
    "width": 1600,
    "height": 602,
    "attribution": "This Image was created by User:Archith. If you would like to use the image please mail me at archithrobber@gmail.com",
    "licence": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tigress_in_Bandhavgarh_NP.jpg"
  },
  "kanha-national-park": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Tiger_Kanha_National_Park.jpg/1920px-Tiger_Kanha_National_Park.jpg",
    "width": 1600,
    "height": 1067,
    "attribution": "Davidvraju",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tiger_Kanha_National_Park.jpg"
  },
  "pachmarhi": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/b4/Pachmarhi_valley_Madhya_Pradesh_INDIA.jpg",
    "width": 1600,
    "height": 1200,
    "attribution": "Abhayashok",
    "licence": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pachmarhi_valley_Madhya_Pradesh_INDIA.jpg"
  },
  "bhimbetka-rock-shelters": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Rock_Shelter_8%2C_Bhimbetka_02.jpg/1920px-Rock_Shelter_8%2C_Bhimbetka_02.jpg",
    "width": 1600,
    "height": 1067,
    "attribution": "Bernard Gagnon",
    "licence": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rock_Shelter_8,_Bhimbetka_02.jpg"
  },
  "mandu": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/JahazMahal.jpg/1920px-JahazMahal.jpg",
    "width": 1600,
    "height": 1200,
    "attribution": "Aamin",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:JahazMahal.jpg"
  },
  "omkareshwar": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Omkareswar_Jyotirlinga.jpg/1920px-Omkareswar_Jyotirlinga.jpg",
    "width": 1600,
    "height": 738,
    "attribution": "Deveshc92",
    "licence": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Omkareswar_Jyotirlinga.jpg"
  },
  "bhedaghat-dhuandhar": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/7/71/Bhedaghat_Jbp.jpg",
    "width": 1600,
    "height": 1067,
    "attribution": "Aksveer",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bhedaghat_Jbp.jpg"
  },
  "bhojpur-temple": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Shiva_Temple%2C_Bhojpur_01.jpg/1920px-Shiva_Temple%2C_Bhojpur_01.jpg",
    "width": 1600,
    "height": 1067,
    "attribution": "Bernard Gagnon",
    "licence": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Shiva_Temple,_Bhojpur_01.jpg"
  },
  "chanderi": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Chanderi_Fort_03.jpg/1920px-Chanderi_Fort_03.jpg",
    "width": 1600,
    "height": 2125,
    "attribution": "GymPediaWarrior",
    "licence": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chanderi_Fort_03.jpg"
  },
  "maheshwar": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Maheshwar_fort.JPG/1920px-Maheshwar_fort.JPG",
    "width": 1600,
    "height": 1066,
    "attribution": "Lukas Vacovsky",
    "licence": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Maheshwar_fort.JPG"
  },
  "satpura-national-park": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Amazing_Landscape_%40Satpura_Tiger_Reserve.jpg/1920px-Amazing_Landscape_%40Satpura_Tiger_Reserve.jpg",
    "width": 1600,
    "height": 900,
    "attribution": "BSSKrishnaS",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Amazing_Landscape_@Satpura_Tiger_Reserve.jpg"
  },
  "pench-national-park": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Pench_Safari.jpg/1920px-Pench_Safari.jpg",
    "width": 1600,
    "height": 900,
    "attribution": "ChanchalJhanwar",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pench_Safari.jpg"
  },
  "amarkantak": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/A_Hindu_temple%2C_Amarkantak_Madhya_Pradesh_India.jpg/1920px-A_Hindu_temple%2C_Amarkantak_Madhya_Pradesh_India.jpg",
    "width": 1600,
    "height": 1069,
    "attribution": "R Singh",
    "licence": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_Hindu_temple,_Amarkantak_Madhya_Pradesh_India.jpg"
  },
  "sonagiri": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/e/e3/Sonagiri.jpg",
    "width": 1600,
    "height": 947,
    "attribution": "Jain cloud",
    "licence": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sonagiri.jpg"
  },
  "udayagiri-caves": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Varahavtar_Panel.jpg/1920px-Varahavtar_Panel.jpg",
    "width": 1600,
    "height": 1071,
    "attribution": "Asitjain",
    "licence": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Varahavtar_Panel.jpg"
  },
  "kuno-national-park": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Kuno_river.jpg/1920px-Kuno_river.jpg",
    "width": 1600,
    "height": 1200,
    "attribution": "M G Chandrasekr",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kuno_river.jpg"
  },
  "chausath-yogini-mitaoli": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Chausath_Yogini_Temple%2C_Mitaoli%2C_Morena_006.jpg/1920px-Chausath_Yogini_Temple%2C_Mitaoli%2C_Morena_006.jpg",
    "width": 1600,
    "height": 1067,
    "attribution": "Suyash Dwivedi",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chausath_Yogini_Temple,_Mitaoli,_Morena_006.jpg"
  },
  "bateshwar-temples": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Bateshwar_Group_of_Temples%2C_Morena%2C_Near_Gwalior.jpg/1920px-Bateshwar_Group_of_Temples%2C_Morena%2C_Near_Gwalior.jpg",
    "width": 1600,
    "height": 1200,
    "attribution": "Anamdas",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bateshwar_Group_of_Temples,_Morena,_Near_Gwalior.jpg"
  },
  "garhkundar-fort": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Garh_Kundar.JPG/1920px-Garh_Kundar.JPG",
    "width": 1600,
    "height": 1200,
    "attribution": "shivanshu kumar singh",
    "licence": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Garh_Kundar.JPG"
  },
  "bhimkund": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Blue_Water_Caves.jpg/1920px-Blue_Water_Caves.jpg",
    "width": 1600,
    "height": 2133,
    "attribution": "Hardanddeeps",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blue_Water_Caves.jpg"
  },
  "dhamnar-caves": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/ba/Dhamnar_Caves_overview.jpg",
    "width": 1600,
    "height": 1063,
    "attribution": "Partner",
    "licence": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dhamnar_Caves_overview.jpg"
  },
  "patalkot": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Patalkot_Green_Valley_View%2C_Chhindwara_District%2C_Madhya_Pradesh%2C_India.jpg/1920px-Patalkot_Green_Valley_View%2C_Chhindwara_District%2C_Madhya_Pradesh%2C_India.jpg",
    "width": 1600,
    "height": 1205,
    "attribution": "Kaushlendrapathe",
    "licence": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Patalkot_Green_Valley_View,_Chhindwara_District,_Madhya_Pradesh,_India.jpg"
  },
  "bagh-caves": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Buddhist_Caves_No.1_to_7_8.JPG/1920px-Buddhist_Caves_No.1_to_7_8.JPG",
    "width": 1600,
    "height": 1067,
    "attribution": "Nikhil2789",
    "licence": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Buddhist_Caves_No.1_to_7_8.JPG"
  },
  "ginnorgarh-fort": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Ginnorgarh_fort_from_the_west.jpg/1920px-Ginnorgarh_fort_from_the_west.jpg",
    "width": 1600,
    "height": 1200,
    "attribution": "Shirazibustan",
    "licence": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ginnorgarh_fort_from_the_west.jpg"
  }
};
